<toggle-button toggle-attributes="data-modal-action:open,close" class="d-lg-none">
  <button type="button" class="icon-button large radius-full"
          aria-label="{{ "Öppna meny" | t }}"
          aria-expanded="false"
          aria-haspopup="true"
          aria-controls="mobile-menu"
          data-action-toggle="true"
          data-modal-overlay="false"
          data-modal-action="open"
          data-modal-element="#main-menu">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path
        d="M3.5 17.6347V16.135H20.5V17.6347H3.5ZM3.5 12.7502V11.2502H20.5V12.7502H3.5ZM3.5 7.86547V6.36572H20.5V7.86547H3.5Z"
        fill="#030712"/>
    </svg>

    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path
        d="M6.4 18.6537L5.34625 17.5999L10.9463 11.9999L5.34625 6.39994L6.4 5.34619L12 10.9462L17.6 5.34619L18.6538 6.39994L13.0538 11.9999L18.6538 17.5999L17.6 18.6537L12 13.0537L6.4 18.6537Z"
        fill="#030712"/>
    </svg>
  </button>
</toggle-button>